// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace AzureSuiteForUnity.CognitiveServices.Emotion.Model
{

    public class RecognizeResponse
    {
        public class FaceRectangle2
        {

            [JsonProperty("Top")]
            public int Top { get; set; }

            [JsonProperty("Left")]
            public int Left { get; set; }

            [JsonProperty("Width")]
            public int Width { get; set; }

            [JsonProperty("Height")]
            public int Height { get; set; }
        }

        public class Scores2
        {

            [JsonProperty("Anger")]
            public double Anger { get; set; }

            [JsonProperty("Contempt")]
            public double Contempt { get; set; }

            [JsonProperty("Disgust")]
            public double Disgust { get; set; }

            [JsonProperty("Fear")]
            public double Fear { get; set; }

            [JsonProperty("Happiness")]
            public double Happiness { get; set; }

            [JsonProperty("Neutral")]
            public double Neutral { get; set; }

            [JsonProperty("Sadness")]
            public double Sadness { get; set; }

            [JsonProperty("Surprise")]
            public double Surprise { get; set; }
        }

        public class Emotion
        {

            [JsonProperty("FaceRectangle")]
            public FaceRectangle2 FaceRectangle { get; set; }

            [JsonProperty("Scores")]
            public Scores2 Scores { get; set; }
        }


        [JsonProperty("Emotions")]
        public IList<Emotion> Emotions { get; set; }

}
    }
