using OpenCVForUnity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace AzureSuiteForUnity.CognitiveServices.Face.Model
{
    /// <summary>
    /// This class isn't autogenerated so we get inheritance on face landmarks
    /// </summary>
    public class DetectResponse
    {
        public class FaceRectangle
        {
            public int top { get; set; }
            public int left { get; set; }
            public int width { get; set; }
            public int height { get; set; }
        }

        public class FaceLandmark
        {
            public float X { get; set; }
            public float Y { get; set; }

            public FaceLandmark() { }
            public FaceLandmark(int x, int y)
            {
                X = x;
                Y = y;
            }

            public Point ToPoint()
            {
                return new Point(X, Y);
            }
        }

        public class PupilLeft : FaceLandmark
        {
        }

        public class PupilRight : FaceLandmark
        {
        }

        public class NoseTip : FaceLandmark
        {
        }

        public class MouthLeft : FaceLandmark
        {
        }

        public class MouthRight : FaceLandmark
        {
        }

        public class EyebrowLeftOuter : FaceLandmark
        {
        }

        public class EyebrowLeftInner : FaceLandmark
        {
        }

        public class EyeLeftOuter : FaceLandmark
        {
        }

        public class EyeLeftTop : FaceLandmark
        {
        }

        public class EyeLeftBottom : FaceLandmark
        {
        }

        public class EyeLeftInner : FaceLandmark
        {
        }

        public class EyebrowRightInner : FaceLandmark
        {
        }

        public class EyebrowRightOuter : FaceLandmark
        {
        }

        public class EyeRightInner : FaceLandmark
        {
        }

        public class EyeRightTop : FaceLandmark
        {
        }

        public class EyeRightBottom : FaceLandmark
        {
        }

        public class EyeRightOuter : FaceLandmark
        {
        }

        public class NoseRootLeft : FaceLandmark
        {
        }

        public class NoseRootRight : FaceLandmark
        {
        }

        public class NoseLeftAlarTop : FaceLandmark
        {
        }

        public class NoseRightAlarTop : FaceLandmark
        {
        }

        public class NoseLeftAlarOutTip : FaceLandmark
        {
        }

        public class NoseRightAlarOutTip : FaceLandmark
        {
        }

        public class UpperLipTop : FaceLandmark
        {
        }

        public class UpperLipBottom : FaceLandmark
        {
        }

        public class UnderLipTop : FaceLandmark
        {
        }

        public class UnderLipBottom : FaceLandmark
        {
        }

        public class FaceLandmarks
        {

            public List<FaceLandmark> FaceLandmarkList()
            {
                var list = new List<FaceLandmark>()
                {
                    pupilLeft, pupilRight,
                    noseTip, mouthLeft, mouthRight,
                    eyebrowLeftOuter, eyebrowLeftInner,
                    eyeLeftOuter, eyeLeftTop,
                    eyeLeftBottom, eyeLeftInner,
                    eyebrowRightOuter, eyebrowRightInner,
                    eyeRightOuter, eyeRightTop,
                    eyeRightBottom, eyeRightInner,
                    noseLeftAlarOutTip, noseLeftAlarTop, noseRightAlarOutTip, noseRightAlarTop,
                    noseRootLeft, noseRootRight, noseTip,
                    upperLipBottom, upperLipTop,
                    underLipBottom, underLipTop
                };

                return list;
            }
            public PupilLeft pupilLeft { get; set; }
            public PupilRight pupilRight { get; set; }
            public NoseTip noseTip { get; set; }
            public MouthLeft mouthLeft { get; set; }
            public MouthRight mouthRight { get; set; }
            public EyebrowLeftOuter eyebrowLeftOuter { get; set; }
            public EyebrowLeftInner eyebrowLeftInner { get; set; }
            public EyeLeftOuter eyeLeftOuter { get; set; }
            public EyeLeftTop eyeLeftTop { get; set; }
            public EyeLeftBottom eyeLeftBottom { get; set; }
            public EyeLeftInner eyeLeftInner { get; set; }
            public EyebrowRightInner eyebrowRightInner { get; set; }
            public EyebrowRightOuter eyebrowRightOuter { get; set; }
            public EyeRightInner eyeRightInner { get; set; }
            public EyeRightTop eyeRightTop { get; set; }
            public EyeRightBottom eyeRightBottom { get; set; }
            public EyeRightOuter eyeRightOuter { get; set; }
            public NoseRootLeft noseRootLeft { get; set; }
            public NoseRootRight noseRootRight { get; set; }
            public NoseLeftAlarTop noseLeftAlarTop { get; set; }
            public NoseRightAlarTop noseRightAlarTop { get; set; }
            public NoseLeftAlarOutTip noseLeftAlarOutTip { get; set; }
            public NoseRightAlarOutTip noseRightAlarOutTip { get; set; }
            public UpperLipTop upperLipTop { get; set; }
            public UpperLipBottom upperLipBottom { get; set; }
            public UnderLipTop underLipTop { get; set; }
            public UnderLipBottom underLipBottom { get; set; }
        }

        public class HeadPose
        {
            public double pitch { get; set; }
            public double roll { get; set; }
            public double yaw { get; set; }
        }

        public class FacialHair
        {
            public double moustache { get; set; }
            public double beard { get; set; }
            public double sideburns { get; set; }
        }

        public class Emotion
        {
            public double anger { get; set; }
            public double contempt { get; set; }
            public double disgust { get; set; }
            public double fear { get; set; }
            public double happiness { get; set; }
            public double neutral { get; set; }
            public double sadness { get; set; }
            public double surprise { get; set; }
        }

        public class Blur
        {
            public string blurLevel { get; set; }
            public double value { get; set; }
        }

        public class Exposure
        {
            public string exposureLevel { get; set; }
            public double value { get; set; }
        }

        public class Noise
        {
            public string noiseLevel { get; set; }
            public double value { get; set; }
        }

        public class Makeup
        {
            public bool eyeMakeup { get; set; }
            public bool lipMakeup { get; set; }
        }

        public class Occlusion
        {
            public bool foreheadOccluded { get; set; }
            public bool eyeOccluded { get; set; }
            public bool mouthOccluded { get; set; }
        }

        public class HairColor
        {
            public string color { get; set; }
            public double confidence { get; set; }
        }

        public class Hair
        {
            public double bald { get; set; }
            public bool invisible { get; set; }
            public List<HairColor> hairColor { get; set; }
        }

        public class FaceAttributes
        {
            public double smile { get; set; }
            public HeadPose headPose { get; set; }
            public string gender { get; set; }
            public double age { get; set; }
            public FacialHair facialHair { get; set; }
            public string glasses { get; set; }
            public Emotion emotion { get; set; }
            public Blur blur { get; set; }
            public Exposure exposure { get; set; }
            public Noise noise { get; set; }
            public Makeup makeup { get; set; }
            public List<object> accessories { get; set; }
            public Occlusion occlusion { get; set; }
            public Hair hair { get; set; }
        }

        public class RootObject
        {
            public string faceId { get; set; }
            public FaceRectangle faceRectangle { get; set; }
            public FaceLandmarks faceLandmarks { get; set; }
            public FaceAttributes faceAttributes { get; set; }
        }
    }
}
