// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace JsonClassGen
{

    public class JsonClassGenConfig
    {
        public class Options2
        {

            [JsonProperty("useproperties")]
            public bool Useproperties { get; set; }

            [JsonProperty("pascal")]
            public bool Pascal { get; set; }

            [JsonProperty("nested")]
            public bool Nested { get; set; }

            [JsonProperty("singlefile")]
            public bool Singlefile { get; set; }

            [JsonProperty("internalvisibility")]
            public bool Internalvisibility { get; set; }
        }

        public class Class
        {

            [JsonProperty("filename")]
            public string Filename { get; set; }

            [JsonProperty("namespace")]
            public string Namespace { get; set; }

            [JsonProperty("mainclass")]
            public string Mainclass { get; set; }
        }


        [JsonProperty("options")]
        public Options2 Options { get; set; }

        [JsonProperty("classes")]
        public IList<Class> Classes { get; set; }

}
    }
