// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace AzureSuiteForUnity.CognitiveServices.ComputerVision.Model
{

    public class DescribeResponse
    {
        public class FaceRectangle2
        {

            [JsonProperty("Top")]
            public int Top { get; set; }

            [JsonProperty("Left")]
            public int Left { get; set; }

            [JsonProperty("Width")]
            public int Width { get; set; }

            [JsonProperty("Height")]
            public int Height { get; set; }
        }

        public class HairColor2
        {

            [JsonProperty("Color")]
            public string Color { get; set; }

            [JsonProperty("Confidence")]
            public double Confidence { get; set; }
        }

        public class Hair2
        {

            [JsonProperty("Bald")]
            public double Bald { get; set; }

            [JsonProperty("Invisible")]
            public bool Invisible { get; set; }

            [JsonProperty("HairColor")]
            public IList<HairColor2> HairColor { get; set; }
        }

        public class HeadPose2
        {

            [JsonProperty("Pitch")]
            public double Pitch { get; set; }

            [JsonProperty("Roll")]
            public double Roll { get; set; }

            [JsonProperty("Yaw")]
            public double Yaw { get; set; }
        }

        public class FacialHair2
        {

            [JsonProperty("Moustache")]
            public double Moustache { get; set; }

            [JsonProperty("Beard")]
            public double Beard { get; set; }

            [JsonProperty("Sideburns")]
            public double Sideburns { get; set; }
        }

        public class Makeup2
        {

            [JsonProperty("EyeMakeup")]
            public bool EyeMakeup { get; set; }

            [JsonProperty("LipMakeup")]
            public bool LipMakeup { get; set; }
        }

        public class Emotion2
        {

            [JsonProperty("Anger")]
            public double Anger { get; set; }

            [JsonProperty("Contempt")]
            public double Contempt { get; set; }

            [JsonProperty("Disgust")]
            public double Disgust { get; set; }

            [JsonProperty("Fear")]
            public double Fear { get; set; }

            [JsonProperty("Happiness")]
            public double Happiness { get; set; }

            [JsonProperty("Neutral")]
            public double Neutral { get; set; }

            [JsonProperty("Sadness")]
            public double Sadness { get; set; }

            [JsonProperty("Surprise")]
            public double Surprise { get; set; }
        }

        public class Occlusion2
        {

            [JsonProperty("ForeheadOccluded")]
            public bool ForeheadOccluded { get; set; }

            [JsonProperty("EyeOccluded")]
            public bool EyeOccluded { get; set; }

            [JsonProperty("MouthOccluded")]
            public bool MouthOccluded { get; set; }
        }

        public class Accessory
        {

            [JsonProperty("Type")]
            public string Type { get; set; }

            [JsonProperty("Confidence")]
            public double Confidence { get; set; }
        }

        public class Blur2
        {

            [JsonProperty("BlurLevel")]
            public string BlurLevel { get; set; }

            [JsonProperty("Value")]
            public double Value { get; set; }
        }

        public class Exposure2
        {

            [JsonProperty("ExposureLevel")]
            public string ExposureLevel { get; set; }

            [JsonProperty("Value")]
            public double Value { get; set; }
        }

        public class Noise2
        {

            [JsonProperty("NoiseLevel")]
            public string NoiseLevel { get; set; }

            [JsonProperty("Value")]
            public double Value { get; set; }
        }

        public class FaceAttributes2
        {

            [JsonProperty("Hair")]
            public Hair2 Hair { get; set; }

            [JsonProperty("Smile")]
            public double Smile { get; set; }

            [JsonProperty("HeadPose")]
            public HeadPose2 HeadPose { get; set; }

            [JsonProperty("Gender")]
            public string Gender { get; set; }

            [JsonProperty("Age")]
            public double Age { get; set; }

            [JsonProperty("FacialHair")]
            public FacialHair2 FacialHair { get; set; }

            [JsonProperty("Glasses")]
            public string Glasses { get; set; }

            [JsonProperty("Makeup")]
            public Makeup2 Makeup { get; set; }

            [JsonProperty("Emotion")]
            public Emotion2 Emotion { get; set; }

            [JsonProperty("Occlusion")]
            public Occlusion2 Occlusion { get; set; }

            [JsonProperty("Accessories")]
            public IList<Accessory> Accessories { get; set; }

            [JsonProperty("Blur")]
            public Blur2 Blur { get; set; }

            [JsonProperty("Exposure")]
            public Exposure2 Exposure { get; set; }

            [JsonProperty("Noise")]
            public Noise2 Noise { get; set; }
        }

        public class PupilLeft2
        {

            [JsonProperty("X")]
            public double X { get; set; }

            [JsonProperty("Y")]
            public double Y { get; set; }
        }

        public class PupilRight2
        {

            [JsonProperty("X")]
            public double X { get; set; }

            [JsonProperty("Y")]
            public double Y { get; set; }
        }

        public class NoseTip2
        {

            [JsonProperty("X")]
            public double X { get; set; }

            [JsonProperty("Y")]
            public double Y { get; set; }
        }

        public class MouthLeft2
        {

            [JsonProperty("X")]
            public double X { get; set; }

            [JsonProperty("Y")]
            public double Y { get; set; }
        }

        public class MouthRight2
        {

            [JsonProperty("X")]
            public double X { get; set; }

            [JsonProperty("Y")]
            public double Y { get; set; }
        }

        public class EyebrowLeftOuter2
        {

            [JsonProperty("X")]
            public double X { get; set; }

            [JsonProperty("Y")]
            public double Y { get; set; }
        }

        public class EyebrowLeftInner2
        {

            [JsonProperty("X")]
            public double X { get; set; }

            [JsonProperty("Y")]
            public double Y { get; set; }
        }

        public class EyeLeftOuter2
        {

            [JsonProperty("X")]
            public double X { get; set; }

            [JsonProperty("Y")]
            public double Y { get; set; }
        }

        public class EyeLeftTop2
        {

            [JsonProperty("X")]
            public double X { get; set; }

            [JsonProperty("Y")]
            public double Y { get; set; }
        }

        public class EyeLeftBottom2
        {

            [JsonProperty("X")]
            public double X { get; set; }

            [JsonProperty("Y")]
            public double Y { get; set; }
        }

        public class EyeLeftInner2
        {

            [JsonProperty("X")]
            public double X { get; set; }

            [JsonProperty("Y")]
            public double Y { get; set; }
        }

        public class EyebrowRightInner2
        {

            [JsonProperty("X")]
            public double X { get; set; }

            [JsonProperty("Y")]
            public double Y { get; set; }
        }

        public class EyebrowRightOuter2
        {

            [JsonProperty("X")]
            public double X { get; set; }

            [JsonProperty("Y")]
            public double Y { get; set; }
        }

        public class EyeRightInner2
        {

            [JsonProperty("X")]
            public double X { get; set; }

            [JsonProperty("Y")]
            public double Y { get; set; }
        }

        public class EyeRightTop2
        {

            [JsonProperty("X")]
            public double X { get; set; }

            [JsonProperty("Y")]
            public double Y { get; set; }
        }

        public class EyeRightBottom2
        {

            [JsonProperty("X")]
            public double X { get; set; }

            [JsonProperty("Y")]
            public double Y { get; set; }
        }

        public class EyeRightOuter2
        {

            [JsonProperty("X")]
            public double X { get; set; }

            [JsonProperty("Y")]
            public double Y { get; set; }
        }

        public class NoseRootLeft2
        {

            [JsonProperty("X")]
            public double X { get; set; }

            [JsonProperty("Y")]
            public double Y { get; set; }
        }

        public class NoseRootRight2
        {

            [JsonProperty("X")]
            public double X { get; set; }

            [JsonProperty("Y")]
            public double Y { get; set; }
        }

        public class NoseLeftAlarTop2
        {

            [JsonProperty("X")]
            public double X { get; set; }

            [JsonProperty("Y")]
            public double Y { get; set; }
        }

        public class NoseRightAlarTop2
        {

            [JsonProperty("X")]
            public double X { get; set; }

            [JsonProperty("Y")]
            public double Y { get; set; }
        }

        public class NoseLeftAlarOutTip2
        {

            [JsonProperty("X")]
            public double X { get; set; }

            [JsonProperty("Y")]
            public double Y { get; set; }
        }

        public class NoseRightAlarOutTip2
        {

            [JsonProperty("X")]
            public double X { get; set; }

            [JsonProperty("Y")]
            public double Y { get; set; }
        }

        public class UpperLipTop2
        {

            [JsonProperty("X")]
            public double X { get; set; }

            [JsonProperty("Y")]
            public double Y { get; set; }
        }

        public class UpperLipBottom2
        {

            [JsonProperty("X")]
            public double X { get; set; }

            [JsonProperty("Y")]
            public double Y { get; set; }
        }

        public class UnderLipTop2
        {

            [JsonProperty("X")]
            public double X { get; set; }

            [JsonProperty("Y")]
            public double Y { get; set; }
        }

        public class UnderLipBottom2
        {

            [JsonProperty("X")]
            public double X { get; set; }

            [JsonProperty("Y")]
            public double Y { get; set; }
        }

        public class FaceLandmarks2
        {

            [JsonProperty("PupilLeft")]
            public PupilLeft2 PupilLeft { get; set; }

            [JsonProperty("PupilRight")]
            public PupilRight2 PupilRight { get; set; }

            [JsonProperty("NoseTip")]
            public NoseTip2 NoseTip { get; set; }

            [JsonProperty("MouthLeft")]
            public MouthLeft2 MouthLeft { get; set; }

            [JsonProperty("MouthRight")]
            public MouthRight2 MouthRight { get; set; }

            [JsonProperty("EyebrowLeftOuter")]
            public EyebrowLeftOuter2 EyebrowLeftOuter { get; set; }

            [JsonProperty("EyebrowLeftInner")]
            public EyebrowLeftInner2 EyebrowLeftInner { get; set; }

            [JsonProperty("EyeLeftOuter")]
            public EyeLeftOuter2 EyeLeftOuter { get; set; }

            [JsonProperty("EyeLeftTop")]
            public EyeLeftTop2 EyeLeftTop { get; set; }

            [JsonProperty("EyeLeftBottom")]
            public EyeLeftBottom2 EyeLeftBottom { get; set; }

            [JsonProperty("EyeLeftInner")]
            public EyeLeftInner2 EyeLeftInner { get; set; }

            [JsonProperty("EyebrowRightInner")]
            public EyebrowRightInner2 EyebrowRightInner { get; set; }

            [JsonProperty("EyebrowRightOuter")]
            public EyebrowRightOuter2 EyebrowRightOuter { get; set; }

            [JsonProperty("EyeRightInner")]
            public EyeRightInner2 EyeRightInner { get; set; }

            [JsonProperty("EyeRightTop")]
            public EyeRightTop2 EyeRightTop { get; set; }

            [JsonProperty("EyeRightBottom")]
            public EyeRightBottom2 EyeRightBottom { get; set; }

            [JsonProperty("EyeRightOuter")]
            public EyeRightOuter2 EyeRightOuter { get; set; }

            [JsonProperty("NoseRootLeft")]
            public NoseRootLeft2 NoseRootLeft { get; set; }

            [JsonProperty("NoseRootRight")]
            public NoseRootRight2 NoseRootRight { get; set; }

            [JsonProperty("NoseLeftAlarTop")]
            public NoseLeftAlarTop2 NoseLeftAlarTop { get; set; }

            [JsonProperty("NoseRightAlarTop")]
            public NoseRightAlarTop2 NoseRightAlarTop { get; set; }

            [JsonProperty("NoseLeftAlarOutTip")]
            public NoseLeftAlarOutTip2 NoseLeftAlarOutTip { get; set; }

            [JsonProperty("NoseRightAlarOutTip")]
            public NoseRightAlarOutTip2 NoseRightAlarOutTip { get; set; }

            [JsonProperty("UpperLipTop")]
            public UpperLipTop2 UpperLipTop { get; set; }

            [JsonProperty("UpperLipBottom")]
            public UpperLipBottom2 UpperLipBottom { get; set; }

            [JsonProperty("UnderLipTop")]
            public UnderLipTop2 UnderLipTop { get; set; }

            [JsonProperty("UnderLipBottom")]
            public UnderLipBottom2 UnderLipBottom { get; set; }
        }


        [JsonProperty("FaceId")]
        public string FaceId { get; set; }

        [JsonProperty("FaceRectangle")]
        public FaceRectangle2 FaceRectangle { get; set; }

        [JsonProperty("FaceAttributes")]
        public FaceAttributes2 FaceAttributes { get; set; }

        [JsonProperty("FaceLandmarks")]
        public FaceLandmarks2 FaceLandmarks { get; set; }

}
    }
